logging:
    level:
        io.github.okooo: DEBUG
server:
    port: 8888
spring:
    application:
        name: okooo
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.76.157.149:3306/lottery?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: lottery
        password: lottery123

# Mybatis配置
mybatis:
    configuration:
        map-underscore-to-camel-case: true
        use-generated-keys: true
    type-aliases-package: io.github.okooo.domain
    mapper-locations: classpath:mapper/*.xml