logging:
    level:
        io.github.okooo: DEBUG
server:
    port: 7001
spring:
    application:
        name: okooo
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/okooo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: okooo
        password: okooo,123

# Mybatis配置
mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    typeAliasesPackage: io.github.okooo.domain
    global-config:
        #驼峰下划线转换
        db-column-underline: true
        #数据库大写下划线转换
        capital-mode: false